Repository Alexhellupov-cyber/goit_portfolio, pull requests merged in 2025-03, with the labels that each got.

#9 Covers
  src/css/reviews.css
  src/img/covers/vectors@1x.png
  src/img/covers/vectors@2x.png
  src/img/reviews/profile-photo.png
  src/index.html
  src/js/reviews-swiper.js
  src/js/reviews.js
  src/main.js
  src/partials/reviews.html
Labels: question

#10 Add FAQ section
  package-lock.json
  package.json
  src/css/faq.css
  src/css/style.css
  src/img/icons.svg
  src/js/faq.js
  src/partials/faq.html
Labels: Time

#5 Projects
  package-lock.json
  package.json
  src/css/projects.css
  src/js/projects.js
  src/partials/projects.html
Labels: bug

#12 Update her header fix and change theme test
  src/css/header.css
  src/css/hero.css
  src/img/hero/hero_green_mob.jpg
  src/js/hero.js
  src/partials/header.html
  src/partials/hero.html
Labels: test

#18 work-together-html&css-complete
  src/css/work-together.css
  src/img/footer/footer-bcg-img-desk.png
  src/img/footer/footer-bcg-img-mob.png
  src/img/footer/footer-bcg-img-tab.png
  src/partials/work-together.html
Labels: Time
